# Example vm-settings.yaml for cloudinit-linux-vm-deploy.ps1
# == Infrastructure (vCenter Connection) ==
# If vcenter_user/vcenter_password are blank or omitted,
# the script will look for cached credentials via New-VICredentialStoreItem.
vcenter_host: vcenter01.backyard.local
vcenter_user: administrator@vsphere.local   # Single Sign-On (SSO) user. Example: administrator@vsphere.local
vcenter_password: "KenFiat50s^"             # SSO password. "" or omit to use credential store.

# == VM Hardware/Placement ==
template_vm_name: rhel9-tpl
new_vm_name: original01
cluster_name: CLST_A
datastore_name: ProdStore
resource_pool_name: Resources   # If you are not sure, leave as "Resources" or comment out.
esxi_host: vhost-a01
## Network port label; set either of the two (not both)
#network_name: VM Network       # For standard switch
dvs_portgroup: PROD_LAN01       # For Distributed Switch
##
cpu: 3
memory_mb: 4096
disk_format: Thick    # One of: Thick, Thin, EagerZeroedThick, or leave blank (or comment the line) to retain template's format
disks:
  - name: Hard disk 1
    size_gb: 45
  #- name: Hard disk 2
  #  size_gb: 6
  - name: Hard disk 3
    size_gb: 5

# == OS/Cloud-init Parameters ==
hostname: original01
instance-id: original01-20251001
fqdn: original01.production.local

ip_addr1: 192.168.0.10
prefix1: 24
gateway1: 192.168.0.254
dns1: 192.168.0.201
dns2: 192.168.0.202

# Additional NIC example (uncomment to use)
# ip_addr2: 10.10.10.101
# prefix2: 24

username: mainte
password: "naks9slewiv"    # As plain string for use with PowerShell logics
password_hash: "$6$Kc8......"      # SHA-512 hashed string for user registration in the guest Linux: Generate using 'openssl passwd -6 "password"'
ssh_key1: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAr..."
# ssh_key2: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI..."

growpart:
  mode: auto
  devices: ['/', 'swap', '/var/crash']

package_update: false
package_upgrade: false

# runcmd:
#   - [ echo, "Hello, cloud-init!" ]
